resolver: lts-4.0
packages:
- '.'

extra-deps: [
 GLFW-b-1.4.7.3
 , bindings-GLFW-3.1.1.4
 , GLUtil-0.8.7
 , OpenGL-2.13.1.0
 , GLURaw-1.5.0.2
 , OpenGLRaw-2.6.0.0
 , ObjectName-1.1.0.0
 , hpp-0.1.0.0
]

